// <auto-generated />
namespace BusLocation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Route2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Route2));
        
        string IMigrationMetadata.Id
        {
            get { return "201612102115429_Route 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
