// <auto-generated />
namespace BusLocation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updateroutevalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateroutevalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201701031621072_Update route validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
