// <auto-generated />
namespace BusLocation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddupdatetoUserRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddupdatetoUserRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201701081405469_Add update to User Request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
